platform:
  - x64
environment:
  global:
    MSYS2_BASEVER: 20150916
  matrix:
    - MSYS2_ARCH: i686
      MSYS2_BITS: 32
      MSYSTEM: MINGW32
      METHOD: cross
    - MSYS2_ARCH: x86_64
      MSYS2_BITS: 64
      MSYSTEM: MINGW64
      METHOD: cross

install:
  - ps: If (($env:METHOD -eq "cross") -and  (Test-Path ("msys" + $env:MSYS2_BITS))){Write-Host "Using cached msys2"}
  - ps: If (($env:METHOD -eq "cross") -and !(Test-Path ("msys" + $env:MSYS2_BITS))){Invoke-WebRequest -UserAgent wget -Uri ("http://kent.dl.sourceforge.net/project/msys2/Base/" + $env:MSYS2_ARCH +  "/msys2-base-" + $env:MSYS2_ARCH + "-" + $env:MSYS2_BASEVER + ".tar.xz") -OutFile "msys2.tar.xz"}
  - ps: If (($env:METHOD -eq "cross") -and !(Test-Path ("msys" + $env:MSYS2_BITS))){&"7z" x msys2.tar.xz}
  - ps: If (($env:METHOD -eq "cross") -and !(Test-Path ("msys" + $env:MSYS2_BITS))){&"7z" x msys2.tar > $nul;&("msys" + $env:MSYS2_BITS + "\usr\bin\bash") -lc "";&("msys" + $env:MSYS2_BITS + "\usr\bin\bash") -lc ("for i in {1..3}; do pacman --noconfirm -Suy autoconf automake mingw-w64-"+ $env:MSYS2_ARCH + "-gcc make zlib-devel python3 && break || sleep 15; done");&("msys" + $env:MSYS2_BITS + "\usr\bin\bash") -lc "pacman --noconfirm -R -s bash-completion tftp-hpa inetutils util-linux tzcode time dash flex pax-git file bsdcpio bsdtar lndir";&("msys" + $env:MSYS2_BITS + "\usr\bin\bash") -lc "yes|pacman --noconfirm -Sc";&("msys" + $env:MSYS2_BITS + "\autorebase.bat");}

build_script:
  - if "%METHOD%"=="cross" msys%MSYS2_BITS%\usr\bin\bash -lc "mkdir /tmp;cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; ./bootstrap; ./configure; make"
  - if "%METHOD%"=="cross" cd %APPVEYOR_BUILD_FOLDER%
  - if "%METHOD%"=="cross" mkdir roswell
  - if "%METHOD%"=="cross" mkdir roswell\lisp
  - if "%METHOD%"=="cross" mkdir roswell\documents
  - if "%METHOD%"=="cross" mkdir roswell\documents\html
  - if "%METHOD%"=="cross" copy src\ros.exe roswell
  - if "%METHOD%"=="cross" copy lisp\*.lisp roswell\lisp
  - if "%METHOD%"=="cross" copy lisp\*.ros  roswell\lisp
  - if "%METHOD%"=="cross" copy documents\html\*.html roswell\documents\html
  - if "%METHOD%"=="cross" copy scripts\chm.ros roswell\documents
  - if "%METHOD%"=="cross" cd %APPVEYOR_BUILD_FOLDER%\roswell
  - if "%METHOD%"=="cross" ros version
  - if "%METHOD%"=="cross" ros setup
  - if "%METHOD%"=="cross" ros version=t run
  - if "%METHOD%"=="cross" ros documents\chm.ros
  - if "%METHOD%"=="cross" "C:\Program Files (x86)\HTML Help Workshop\hhc.exe" documents\roswell.hhp || copy nul nul > nul
  - if "%METHOD%"=="cross" cd %APPVEYOR_BUILD_FOLDER%
  - if "%METHOD%"=="cross" 7z a Roswell-%MSYS2_ARCH%.zip roswell/ros.exe roswell/lisp/*.* roswell/documents/roswell.chm
  - if "%METHOD%"=="ci" C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; ./bootstrap; ./configure; make; make install"

test_script:
  - if "%METHOD%"=="ci" C:\msys64\usr\bin\bash -lc "ros version"
  - if "%METHOD%"=="ci" C:\msys64\usr\bin\bash -lc "ros setup"
  - if "%METHOD%"=="ci" C:\msys64\usr\bin\bash -lc "ros install sbcl"
  - if "%METHOD%"=="cross" cd %APPVEYOR_BUILD_FOLDER%\roswell
  - if "%METHOD%"=="cross" ros config
  - if "%METHOD%"=="cross" ros install sbcl
#  - ros install sbcl
#  - ros config
#  - ros -s prove-asdf -s quri-test -e "(asdf:test-system :quri-test)"
#  - ps: foreach($artifactName in $artifacts.keys) { Write-Host $artifacts[$artifactName].path }

artifacts:
  - path: Roswell-x86_64.zip
    name: Roswell-x86_64.zip
  - path: Roswell-i686.zip
    name: Roswell-i686.zip

#cache:
#  - msys64
#  - msys32
#  - msys32 -> .appveyor.yml
#  - msys64 -> .appveyor.yml
